/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linear.regression;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println("Hola");
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {

        LinearRegresion regresion = new LinearRegresion();

        Scene scene = new Scene(regresion);

        stage.setScene(scene);
        stage.setMaximized(true);
        stage.show();
    }
}
